apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: health-diary-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-diary-client
  template:
    metadata:
      labels:
        app: health-diary-client
        tier: frontend
    spec:
      containers:
        - name: health-diary-client
          image: health-diary-client:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "200m"