apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: health-diary-client
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: client-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20