apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: weight-diary
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: weight-diary-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 20